name: run-tests-on-each-nodejs-version
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [ '12', '14' ]
    name: Run tests on Node.js v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test-on-ci